name: Call sync on OpenDataHub CFO fork sync
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Sync-fork
        run: |
          gh workflow run sync-fork.yaml --repo github.com/opendatahub-io/codeflare-operator --ref main
        env:
          GITHUB_TOKEN: ${{ secrets.CODEFLARE_MACHINE_ACCOUNT_TOKEN }}
        shell:
          bash
